# Generated by Django 3.2.6 on 2022-01-06 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsapp',
            fields=[
                ('img', models.ImageField(upload_to='')),
                ('breadcrumb', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
