# Generated by Django 3.2.6 on 2022-01-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_rename_newsapp_newscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontent',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
